version: '3'

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8080:8080"

    
