version: '3'

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    external_links:
      - openldap:ldap.luochunhui.com
    volumes:
      - /srv/docker/jenkins/home:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8080:8080"
    networks:
      - default
      - ldap_user

networks:
  ldap_user:
    external: true
    