apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jenkins
    spec:
      containers:
      - image: registry.cn-shanghai.aliyuncs.com/giko/jenkins:0.0.2
        name: jenkins
        ports:
        - containerPort: 50000
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home-pvc
      imagePullSecrets:
        - name: aliyunregsecret
      restartPolicy: Always
      volumes:
      - name: jenkins-home-pvc
        persistentVolumeClaim:
          claimName: jenkins-home-pvc
status: {}
